#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=charm;size=3;", "id=feet;size=1", "id=extra;size=0", "id=hands;size=2", "id=quiver;size=0", "id=belt;size=1"]

